# file: gunicorn/tasks/package.yml

- name: gunicorn | add package repository
  apt_repository: repo='ppa:gunicorn/ppa'
  sudo: yes

- name: gunicorn | Make sure the packages are installed (Debian)
  apt:
    pkg: gunicorn
    state: present
  sudo: yes
