# file: gunicorn/tasks/source.yml

- name: gunicorn | download gunicorn source
  get_url:
    url: "{{gunicorn_install_url}}"
    dest: "/tmp/gunicorn.tar.gz"
  sudo: yes

- name: gunicorn | Extract tarball
  command: tar -xvzf /tmp/gunicorn.tar.gz
  sudo: yes

- name: gunicorn | Install gunicorn
  command: python /tmp/gunicorn/setup.py install
  sudo: yes
