# file: gunicorn/tasks/source.yml

- name: gunicorn | Install gunicorn from source
  get_url:
    url: "{{gunicorn_install_url}}"
    dest: "/tmp/gunicorn.tar.gz"

- name: gunicorn | Extract tarball
  command: tar -xvzf gunicorn.tar.gz

- name: gunicorn | Install gunicorn
  command: python /tmp/gunicorn/setup.py install
  sudo: yes
